id: I4364458B
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:56:08.275795'
last_modified: '2022-05-30T18:56:08.275800'
parser: null
source_metadata:
  title: Drukpa Kunley Series
  language: bo
  description: 'Texts by and about the controversial yogi and self-proclaimed ''madman''
    Drukpa Kunga Lekpa (''brug pa kun dga'' legs pa, 1455–1529), popularly known as
    Drukpa Kunley:'
  volume:
    fC6BD:
      title: Prayer to Drukpa Kunley
      base_file: fC6BD.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
